import { createElement } from '@lwc/engine-dom';
import CNS_LWC_MasterDataDisplay from 'c/cNS_LWC_MasterDataDisplay';

describe('c-c-n-s-l-w-c-master-data-display', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-c-n-s-l-w-c-master-data-display', {
            is: CNS_LWC_MasterDataDisplay
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});